# assumes the same organization 
environment-info-org: cloudposse
environment-info-repo: infra-live
implementation_path: .github/environments
implementation_file: ecspresso.yaml
implementation_ref: main
