name: Hotfix Branch
on:
  pull_request:
    branches: ["release/**"]
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  do:
    uses: ./.github/workflows/ecspresso-hotfix-branch.yml
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      open: ${{ github.event.pull_request.state == 'open' }}
      labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      ref: ${{ github.event.pull_request.head.ref  }}
      app: "example-${{ github.event.repository.name }}"
      use-partial-taskdefinition: ${{ vars.USE_PARTIAL_TASK_DEFINITIONS || "false" }}
      # enable-migration: false # defaults to false
      # support-rollback: false # defaults to false
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_AND_PRIVATE_REPO_ACCESS_TOKEN_REPO }}"
      registry: "${{ secrets.ECR_REGISTRY }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
      ecr-region: "${{ secrets.ECR_REGION }}"
      ecr-iam-role: "${{ secrets.ECR_IAM_ROLE }}"
