name: Release
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  perform:
    uses: cloudposse/github-actions-workflows-docker-ecr-spacelift/.github/workflows/release.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      version: ${{ github.event.release.tag_name }}
      spacelift-organization: "${{ github.event.repository.owner.login }}"
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_AND_PRIVATE_REPO_ACCESS_TOKEN_REPO }}"
      registry: "${{ secrets.ECR_REGISTRY }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
      ecr-region: "${{ secrets.ECR_REGION }}"
      ecr-iam-role: "${{ secrets.ECR_IAM_ROLE }}"
      spacelift-api-key-id: ${{ secrets.SPACELIFT_API_KEY_ID }}
      spacelift-api-key-secret: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
