name: 🐛 Validate
on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

# Concurrency ensures only the latest push for this PR will run at a time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  codeowners:
    name: "codeowners"
    runs-on: ["ubuntu-latest"]
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v4
      # Leave pinned at 0.7.1 until https://github.com/mszostok/codeowners-validator/issues/173 is resolved
    - uses: mszostok/codeowners-validator@v0.7.1
      if: github.event.pull_request.head.repo.full_name == github.repository
      name: "Full check of CODEOWNERS"
      with:
        # For now, remove "files" check to allow CODEOWNERS to specify non-existent
        # files so we can use the same CODEOWNERS file for Terraform and non-Terraform repos
        #   checks: "files,syntax,owners,duppatterns"
        #checks: "syntax,owners,duppatterns"
        checks: "syntax,duppatterns"
        # GitHub access token is required only if the `owners` check is enabled
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      # Leave pinned at 0.7.1 until https://github.com/mszostok/codeowners-validator/issues/173 is resolved
    - uses: mszostok/codeowners-validator@v0.7.1
      if: github.event.pull_request.head.repo.full_name != github.repository
      name: "Syntax check of CODEOWNERS"
      with:
        checks: "syntax,duppatterns"

  docs:
    name: "docs"
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@v1.16.25
        with:
          files: |
            README.yaml
            ./docs
